# Generated by Django 3.2.19 on 2023-07-18 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_category_menu'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='booking',
            name='unique_booking_created_by',
        ),
    ]
